### PR TITLE
Include Susy

### PR DESCRIPTION
**Pull request by lachieh**

### CODE REVIEW

**Comment by jomurgel** [comment]
@lachieh You know what, I build with Susy normally.  Wasn't sure how wide-spread it was (or in the case of co-workers, how many people prefer bootstrap.  I’ve been considering integrating Susy into this theme (or a second option) just haven’t had a whole lot of time to put into non-day-job-related tasks.

**Comment by lachieh** [comment]
Yeah, that's what I figured. It seems to be that if people are using SASS, they are using some sort of grid system to compliment it and Susy just happens to be the best out there.

I'm about to start another build, and I've used Susy on the last few so I figured it was time to stop repeating myself. I'll spend some time getting it to a workable state and then you can merge the PR.

**Comment by lachieh** [comment]
@jomurgel It looks like there isn't actually anything to do, really.  Because this theme is so bare-bones, it's just a matter of including it. This compiles correctly so it should be good to merge.

**Comment by jomurgel** [comment]
@lachieh thanks!  I'll take a look.

**Comment by lachieh** [comment]
Just had a chance to go over v3. Awesome job, mate. Loving all the additions. Well documented on the susy include too!

**Comment by jomurgel** [comment]
Cheers!  Likewise!  Some of your additions have been phenomenal.

**Pull request closed without merging**
